version: '3.8'
networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.12.16.0/22
services:
  hedge-bot:
    build: .
    container_name: hyperliquid-pacifica-bot
    tty: true
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./:/app/
    environment:
      - PYTHONUNBUFFERED=1
